project:
  type: website
  output-dir: docs

website:
  title: "Megan Hokama"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - cv.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

# 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 