project:
  type: website
  output-dir: docs

website:
  favicon: images/icon.png
  navbar:
    logo: images/icon.png
    title: Megan Hokama
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - CV.qmd

format:
  html:
    theme: 
      light: minty
      dark: [minty, theme-dark.scss]
    css: styles.css
    toc: true

editor: visual

